version: 2

sources:
  - name: powerflow    #name of the source you will reference in the models
    database: powerflow #name of database
    schema: public
    tables:   #name all of the tables you would reference in the models
      - name: registrations
      - name: appsflyer_raw
      - name: google_ads
      - name: transactions
models:
  - name: registrations_clean
    columns: 
      - name: user_id
        tests: #tests that would be run on the column
          - unique 
  - name: marketing_attribution 
    columns: 
      - name: device_id
        tests:
          - unique
          - not_null
      - name: attribution_cost
        tests:
          - not_null
  - name: ltv
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: roi
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi
        tests:
           - not_null
          